kafka:
  pool: nav-dev
cluster: dev-gcp
ingresses: |
  ingresses:
    - https://tiltakspenger-dokument.intern.dev.nav.no
endpoints:
  pdf: http://tiltakspenger-pdfgen
  joark: https://dokarkiv.dev-fss-pub.nais.io
outboundExternalUrls:
  dokarkiv: dokarkiv.dev-fss-pub.nais.io
audience:
  joark: dev-fss:teamdokumenthandtering:dokarkiv
scope:
  joark: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default