apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltakspenger-dokument
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  image: {{ image }}
  port: 8080
  {{ ingresses }}
  azure:
    application:
      enabled: true
  liveness:
    path: /isalive
  readiness:
    path: /isready
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 1
    max: 1
  kafka:
    pool: {{ kafka.pool }}
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: tiltakspenger-soknad-api
          namespace: tpts
          cluster: {{ cluster }}
    outbound:
      rules:
        - application: tiltakspenger-pdfgen
      external:
        - host: {{outboundExternalUrls.dokarkiv}}
  env:
    - name: JOARK_ENDPOINT_URL
      value: {{ endpoints.joark }}
    - name: JOARK_AUDIENCE
      value: {{ audience.joark }}
    - name: JOARK_SCOPE
      value: {{ scope.joark }}
    - name: PDF_ENDPOINT_URL
      value: {{ endpoints.pdf }}
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 512Mi
